services:
  auth_db:
    image: postgres:15
    container_name: "${AUTH_DATABASE_HOST}"
    environment:
      POSTGRES_USER: "${AUTH_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${AUTH_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${AUTH_POSTGRES_DB}"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:${AUTH_POSTGRES_PORT}"
    networks:
      - app-network
  
  auth_migrate:
    build:
      context: ./auth_service 
    platform: linux/amd64
    depends_on:
      - auth_db 
    env_file:
      - .env
    volumes:
      - ./auth_service/alembic/versions:/app/alembic/versions
    networks:
      - app-network
    command: ["/bin/sh", "-c", "alembic revision --autogenerate -m \"Migration\" && alembic upgrade head"]

  auth_service:
    build:
      context: ./auth_service
    platform: linux/amd64
    container_name: ${AUTH_SERVICE_HOST}
    env_file:
      - .env
    depends_on:
      - auth_db
      - auth_migrate
    volumes:
      - ./logs/auth_service:${LOGS_DIR}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    networks:
      - app-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${AUTH_SERVICE_PORT}"]


  transaction_db:
    image: postgres:15
    container_name: ${TRANS_DATABASE_HOST} 
    environment:
      POSTGRES_USER: ${TRANS_POSTGRES_USER} 
      POSTGRES_PASSWORD: ${TRANS_POSTGRES_PASSWORD} 
      POSTGRES_DB: ${TRANS_POSTGRES_DB} 
    volumes:
      - transaction_db_data:/var/lib/postgresql/data
    ports:
      - "5433:${TRANS_POSTGRES_PORT}"
    networks:
      - app-network

  transaction_migrate:
    build:
      context: ./transaction_service 
    platform: linux/amd64
    depends_on:
      - transaction_db 
    env_file:
      - .env
    volumes:
      - ./transaction_service/alembic/versions:/app/alembic/versions
    networks:
      - app-network
    command: ["/bin/sh", "-c", "alembic revision --autogenerate -m \"Migration\" && alembic upgrade head"]

  transaction_service:
    build:
      context: ./transaction_service
    container_name: ${TRANS_SERVICE_HOST}
    env_file:
      - .env
    depends_on:
      - transaction_db
      - transaction_migrate
      - auth_service
    volumes:
      - ./logs/transaction_service:${LOGS_DIR}
    ports:
      - "${TRANS_SERVICE_PORT}:${TRANS_SERVICE_PORT}"
    networks:
      - app-network
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${TRANS_SERVICE_PORT}"]

volumes:
  auth_db_data:
  transaction_db_data:

networks:
  app-network:
    driver: bridge
